# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MRNBike' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MRNBike
pod 'Charts'
pod 'XLPagerTabStrip', '~> 7.0'

end
